# Travis-CI configuration file for VGMTrans

#os:
#  - osx

osx_image: xcode7.1

language:
  - objective-c

#env:
#  - CMAKE_PREFIX_PATH="/usr/local/opt/qt5"

#before_install:
#  - brew update

#install:
#  - brew install qt5
#  - brew install fluidsynth

script:
  - mkdir build && cd build
  - sh ../extras/package/macosx/build.sh -q
