
environment:
  MINGW: C:\Qt\Tools\mingw492_32
  matrix:
    - RUN_CMD: "C:\\MinGW\\msys\\1.0\\bin\\sh --login /c/projects/vgmtrans/.msys_build.sh"
    - RUN_CMD: "\"C:\\Program Files (x86)\\MSBuild\\12.0\\Bin\\MSBuild.exe\" \"src\\VGMTrans_WTL.sln\" /verbosity:minimal /logger:\"C:\\Program Files\\AppVeyor\\BuildAgent\\Appveyor.MSBuildLogger.dll\""

#install:
#  - cmd: SET PATH="C:\Qt\5.5\mingw492_32\bin"

build_script:
  - set PATH=%MINGW%\bin;%PATH%
  - cmd: call %RUN_CMD%